package com.data_management;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 * Reads patient data from files generated by FileOutputStrategy.
 * Each file corresponds to a data label (e.g., "ECG.txt", "Saturation.txt").
 * Each line format: Patient ID: %d, Timestamp: %d, Label: %s, Data: %s
 * "triggered"/"resolved" string values are stored as 1.0 and 0.0 respectively.
 */
public class FileDataReader implements DataReader {

    private final String directory;

    /**
     * @param directory the path to the directory containing the output files
     */
    public FileDataReader(String directory) {
        this.directory = directory;
    }

    /**
     * Reads all .txt files in the configured directory and stores parsed records
     * into the given DataStorage instance.
     *
     * @param dataStorage the storage where data will be stored
     * @throws IOException if the directory cannot be read
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        File dir = new File(directory);
        File[] files = dir.listFiles((d, name) -> name.endsWith(".txt"));
        if (files == null) {
            throw new IOException("Directory not found or not readable: " + directory);
        }
        for (File file : files) {
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    parseLine(line, dataStorage);
                }
            }
        }
    }

    /**
     * Parses a single line and adds the record to dataStorage.
     * Silently skips malformed lines.
     */
    private void parseLine(String line, DataStorage dataStorage) {
        try {
            int idStart = "Patient ID: ".length();
            int idEnd = line.indexOf(',', idStart);
            int patientId = Integer.parseInt(line.substring(idStart, idEnd).trim());

            int tsStart = line.indexOf("Timestamp: ") + "Timestamp: ".length();
            int tsEnd = line.indexOf(',', tsStart);
            long timestamp = Long.parseLong(line.substring(tsStart, tsEnd).trim());

            int labelStart = line.indexOf("Label: ") + "Label: ".length();
            int labelEnd = line.indexOf(',', labelStart);
            String label = line.substring(labelStart, labelEnd).trim();

            int dataStart = line.indexOf("Data: ") + "Data: ".length();
            String dataStr = line.substring(dataStart).trim();

            double value;
            if ("triggered".equalsIgnoreCase(dataStr)) {
                value = 1.0;
            } else if ("resolved".equalsIgnoreCase(dataStr)) {
                value = 0.0;
            } else {
                value = Double.parseDouble(dataStr);
            }

            dataStorage.addPatientData(patientId, value, label, timestamp);
        } catch (Exception e) {
            System.err.println("Skipping malformed line: " + line);
        }
    }
}
